apply plugin: 'com.android.library'
apply from: '../build.androidVersionCommon.gradle'

android {
    namespace 'org.firstinspires.ftc.apriltag'
}

dependencies {
    /*
     * Other Modules
     */
    implementation project(':RobotCore')

    /*
     * External
     */
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    api 'org.openftc:easyopencv:1.7.3'
    api 'org.openftc:apriltag:2.1.0'
}
