apply plugin: 'com.android.library'
apply from: '../build.androidVersionCommon.gradle'

android {
    namespace 'org.firstinspires.inspection'

    defaultConfig {
        versionCode 115
        versionName "23.1"
    }
}

dependencies {
    /*
     * Other Modules
     */
    implementation project(':Hardware')
    implementation project(':RobotCore')

    /*
     * External
     */
    implementation fileTree(include: ['*.jar'], dir: 'libs')

    implementation 'com.journeyapps:zxing-android-embedded:4.3.0'
    implementation 'io.github.ehn-digital-green-development:base45:0.0.3'
}
