apply plugin: 'com.android.library'
apply from: '../build.androidVersionCommon.gradle'

android {
    namespace 'com.google.blocks.ftcrobotcontroller.onbotjava'

    defaultConfig {
        versionCode 75
        versionName "15.1"
    }
}

dependencies {
    /*
     * Other Modules
     */
    implementation project(':RobotCore')
    implementation project(':RobotServer')
    implementation project(':Blocks')

    /*
     * External
     */
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.tools:r8:2.1.75'
    coreLibraryDesugaring 'com.android.tools:desugar_jdk_libs:1.1.1'
}
