import java.text.SimpleDateFormat

//
// build.gradle in FtcRobotController
//
apply plugin: 'com.android.library'
apply from: '../build.androidVersionCommon.gradle'

android {
    defaultConfig {
        buildConfigField "String", "APP_BUILD_TIME", '"' + (new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSZ", Locale.ROOT).format(new Date())) + '"'
    }

    namespace 'com.qualcomm.ftcrobotcontroller'
}

dependencies {
    /*
     * Other Modules
     */
    implementation project(':FtcCommon')
    implementation project(':RobotCore')
    implementation project(':Inspection')
    implementation project(':Blocks')
    implementation project(':Hardware')
    implementation project(':OnBotJava')
    implementation project(':RobotServer')
    implementation project(':Vision')

    /*
     * External
     */
    implementation fileTree(include: ['*.jar'], dir: 'libs')
}
